### ISSUE TITLE
'int' object is not subscriptable

### ISSUE THREAD

**Issue by alexpmagalhaes** [ryanemenecker/dodo#3]
Hey I am running into a problem when using pdb-from-name on cepba

command: pdb-from-name human cebpa -o ./cebpa.pdb

Error is:

`Predicting folded reigons, loops, and IDRs using AF2 structure information.
Building new structure.
{'idr_1': 0, 'idr_2': 357}
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/envs/DODO/bin/pdb-from-name", line 8, in <module>
    sys.exit(pdb_from_name())
  File "/usr/local/Caskroom/miniforge/base/envs/DODO/lib/python3.10/site-packages/dodo/pdb_from_name.py", line 43, in pdb_from_name
    build_pbd_from_name(protein_name, out_path=args.out_path, mode=args.mode,
  File "/usr/local/Caskroom/miniforge/base/envs/DODO/lib/python3.10/site-packages/dodo/build.py", line 107, in pdb_from_name
    PDBParserObj = build_structure(PDBParserObj, mode=mode,
  File "/usr/local/Caskroom/miniforge/base/envs/DODO/lib/python3.10/site-packages/dodo/idr_constructor.py", line 1363, in build_structure
    PDBParserObj=remove_IDRs_loops(PDBParserObj)
  File "/usr/local/Caskroom/miniforge/base/envs/DODO/lib/python3.10/site-packages/dodo/idr_constructor.py", line 101, in remove_IDRs_loops
    if cur_idr[-1]==len(seq)-1:
TypeError: 'int' object is not subscriptable
`

The machine is an intel mac running python 3.10 in a conda environment.

Thank you

**Comment by ryanemenecker** [comment]
Hi alexpmagalhaes,

I just pushed an update that should fix your problem. I tried running the exact command that you had an issue with, and after the update it worked just fine. Thank you for reporting the bug and for passing on relevant info to make it a quick and easy fix!

To get the fix to work you'll need to reinstall DODO. You should be able to just run:

`pip install git+https://github.com/ryanemenecker/dodo.git`

and it should work after install is complete! Let me know if you have any additional problems. 

Best,
ryanemenecker
